from Parallel_Coordinates_Plot import Parallel_Coordinates_Plot
from Advanced_Parallel_Coordinates import Advanced_Parallel_Coordinates
from Graph_SubPlots import Graph_SubPlots
from Graph_SubPlots2 import Graph_SubPlots2


Parallel_Coordinates_Plot()
Advanced_Parallel_Coordinates()
Graph_SubPlots()
Graph_SubPlots2()